### ISSUE TITLE
Not dependency free

### ISSUE THREAD

**Issue by mpolichette** [camwiegert/in-view#11]
Hey this is pretty cool!

Just thought I'd mention, you list 'dependency free' in the readme, but you do have a dependency on lodash.  You could also probably use one of the smaller lodash modules since you only use throttle. 
https://www.npmjs.com/package/lodash.throttle

In any case, thanks!

**Comment by camwiegert** [comment]
@mpolichette Thanks! I see what you mean. When I say that this package is dependency-free, I mean that it's dependency-free for end-users (developers) because everything is bundled with the library.

It has an internal dependency on lodash's `throttle` method, but that should be transparent  to anyone utilizing the library.

And, regarding `lodash.throttle`, my understanding is that importing `lodash/throttle` from the `lodash` package is largely the same. We're also optimizing the bundling of `lodash` modules with [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by anseki** [comment]
Hi, thank you for the useful library.

I think, the `lodash` in `package.json` should be moved to `devDependencies` from `dependencies`.
Some package managers try to install the unneeded `lodash` when the `in-view` is installed. We have to remove it every time.
All bundled libraries are typically added to `devDependencies`.
