### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by camwiegert** [camwiegert/in-view#27]
I'm opening this issue to discuss the roadmap to a 1.0.0 release. What does the API look like? How can we maximize flexibility while minimizing API surface area and handling performance responsibly?

Here are my initial thoughts on API:
### Options
- **threshold** - How much of an element needs to intersect the viewport (+/- offset). This is currently >0.
- **offset** - Offset from the viewport edge. Currently you can set globally with a number or per-direction with an object. I'd like to get to a place where we add transforms to accept units other than pixels.
- **test** - Can we accept a custom test instead of inViewport? What would be the signature of this?
- **container** - Accept a custom container to check visibility against, defaulting to `window`.
### Methods
-  **inView.set([options])** - Instead of implementing methods to update `offset`, `threshold`, and `test` individually, set all of them with this method and an options object.
-  **inView.is(<element>, [options])** - Should use current global options, but also accept an options object for custom checking.
-  **inView(<selector>).set([options])** - Options can be set per-selector as well, defaulting to the global options.
-  **inView(<selector>).on(<event>, <handler>)** - As is.
-  **inView(<selector>).once(<event>, <handler>)** - As is.
-  **inView(<selector>).emit(<event>, <element>)** - As is.
-  **inView(<selector>).check([options])** - Just like `.is`, accept an options object for custom checking, falling back to per-selector or global options.

---

Most of the changes here are to the way we handle options. We'd default to global when per-selector settings aren't set, and add the ability to override both when manually checking with `.is` or `Registry.check`.

I'd also like to add a set of demos, stress tests, and a more comprehensive test suite.

Feedback appreciated!

**Comment by VanBronckhorst** [comment]
What about the custom container mentioned in #20 ? It could be one of the options.

**Comment by camwiegert** [comment]
@VanBronckhorst Yup, missed that one. I'll add it to the list. Thanks!

**Comment by masterofshapes** [comment]
Does this work on mobile as well?

**Comment by camwiegert** [comment]
@masterofshapes Yes, it should work on mobile. Please create a new issue with more details if you don't mind.

**Comment by camwiegert** [comment]
To start moving toward v1, I'm going to open a `v1` branch and rewrite tests for the new API, then we can start making PRs against that.

**Comment by kmohrf** [comment]
hey @camwiegert. any chance you might reconsider #24/#25, given the fact that it may take some time to get the v1 branch out?

**Comment by camwiegert** [comment]
@kmohrf I just opened a PR that adds a `test` method. (#40) I'd appreciate any feedback you have.

I'd like to cap the API here until we reach `v1`, where the option methods can be consolidated to a single, top-level `set` method and prevent API creep.

**Comment by autarc** [comment]
How about passing the options for a new inView instance directly at the creation as a secondary parameter? Like `inView(<selector>, <options>)`. Wouldn't extend the API surface too much while simplify the implementation of default and custom options.

**Comment by sahandnayebaziz** [comment]
This library is great so far :)

I'd like to add that a `.destroy()` or `.off()` method as mentioned in #50 and #54 is necessary for using this on a page with dynamic elements, especially those built with React.

**Comment by kmohrf** [comment]
@sahandnayebaziz any reason that would make you prefer `off()` over `on()` returning callbacks to remove the event listener? because imho it’s quite tiresome to keep track of listeners for use with `off()`. the [delegate](https://www.npmjs.com/package/delegate) library is a good example for this kind of api.

**Comment by camwiegert** [comment]
@sahandnayebaziz I tend to agree with @kmohrf about `on()` returning a callback, unless you've got a use case for `off()` or `destroy()`.

**Comment by sahandnayebaziz** [comment]
Nope, no case for `off()` or `destroy()`! That sounds great @kmohrf @camwiegert.

**Comment by sahandnayebaziz** [comment]
In fact, now that you say that @kmohrf I totally agree. Way better than having to call `off` on a specific listener. What I had in mind was just the ability to remove listeners in whatever way. 

On the topic, @camwiegert, I'm not sure if this fits in to your vision of how in-view should work but as someone importing the library, I would expect all the current selectors I have registered to be accessible in an array or object so that I could do things like remove all of them at once, or check to see if one has been registered already. So I wouldn't expect in-view to have a bunch of functions that answer these questions, but that it would expose the data structure the selectors are saved in so I can work with them in really specific ways if needed.

By the way, I think it's great the way you have this all set up. Bravo

**Comment by ericdfields** [comment]
Just wondering if there's still being work done on this project. It's been helpful to me. What can I do to support it?
